apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi  ##Dummy, Size is Elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" ## should be empty in static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09d30c3262e0c60ea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" ## should be empty in static
  resources:
    requests:
      storage: 5Gi