apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx
  namespace: safety
  labels: 
    name: nginx
    project: safety
spec:
  containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80 ## we can use any port 