apiVersion: v1
kind: pod
metadata:
  name: multi-container
  labels: 
    purpose: multi-container
spec:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","10"]