apiVersion: v1
kind: Pod
metadata: 
  name: resource-test
spec:
  containers:
  - name: nginx
    image: inginx
    resources:
      requests:
        memory: "68Mi"
        cpu: "100m" 
      limits:
        memory: "100Mi"
        cpu: "120m"

