apiVersion: v1 
kind: Service
metadata: 
  name: nginx
spec:
  selector:
    project: safety
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port