apiVersion: v1 
kind: Service
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: safety
    component: frontend
    environment: dev
    purpose: node-port
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port