apiVersion: v1 
kind: Service
metadata: 
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: safety
    component: frontend
    environment: dev
    purpose: load-balancer
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port
      NodePort: 30007