apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: nginx
# these are replica set labels
  labels:
    purpose: rs-demo
    project: safety
spec:
  replicas: 5
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: rs-demo
      project: safety
    # pod definition
  template: 
    metadata:
      labels:
        purpose: rs-demo
        project: safety
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl